exec_always {
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface gtk-theme "$gtk-theme"
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface icon-theme "$icon-theme"
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface cursor-theme "$cursor-theme"
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface font-name "$gui-font"
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface color-scheme "$gtk-color-scheme"
  command -v gsettings >/dev/null 2>&1 && gsettings set org.gnome.desktop.interface monospace-font-name "$term-font"
  command -v kvantummanager >/dev/null 2>&1 && kvantummanager --set "$kvantum-theme"
}
