# autostart background applications
exec sh -c 'for a in lxqt-policykit-agent /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 /usr/libexec/polkit-gnome-authentication-agent-1; do command -v "$a" >/dev/null 2>&1 && exec "$a"; done'

# autostarts
exec {
    $xdg-dirs
    $swayidle
    $mako
    $swayosd
    $autostart_dex
    $wlsunset
    $autotiling
    $foot_server
    $cliphist_store_text
    $cliphist_store_image
    $mounting_daemon
    $dropbox_daemon
}

exec_always {
    $kanshi
    $auto_xdg_keyboard
    $poweralert
    $watch_playerctl
    $calendar_daemon
    $waybar_start
    $waybar_watchdog
}
